---
- hosts: all
  #vars:
  # - 
  roles:
    - update
    - ufw
    - users
    - nginx
    - docker
    - docker-compose
    - restart-services
    - ssh
- hosts: 127.0.0.1
  roles:
    - change_inventory
- hosts: all
  roles:
    - reboot-machine
  tasks:
  - name: END
    file:
      path: /home/touch
