- name: add user 1
  user:
    name: Webdeveloper
    password: S52we9V6QTp7
    shell: /bin/bash
- name: add user 2
  user:
    name: Devopsengineer
    password: dHy6sKGHsj2T
    shell: /bin/bash
- name: add user 3
  user:
    name: Projectmanager
    password: oP92ugMSaCbe #"{{ password_hash('sha512') }}"
    shell: /bin/bash
    #- name: create folder for keys
    # file:
    # path: /home/ '{{ item }}'/.ssh
    # state: directory
    # with_items:
    # - Webdeveloper
    # - Devopsengineer
    # - Projectmanager

    #- name: generate keys
    # openssh_keypair:
    # path: /home/ '{{ item }}'/.ssh/id_rsa.pub
  #shell: sudo -u '{{ item }}' ssh-keygen |
  # yes
  # $'\n'
  # $'\n'
  #  with_items:
  #  - Webdeveloper
  #  - Devopsengineer
  #  - Projectmanager


      #- name: add publickey
      #lineinfile:
      #create: yes
      #line: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCovvBkeLIDsvbCyQsMWtPWVgGVKcwAqRONiBJ9JyrVCQbruyMPutatjSlhNpYXKLlP4BXHrGrmAVqeI155li1fkNP5Il7viHRE0HvA3M2extNGDDCiX5f5OlIeT9p/D9OHvWWozLjN2NAGEW24feuzKPZb6Kyv2W3yHbiIU3wt8v50VAIA2+PAfElHp1jplGHQLmYuT6Cc26Pn3WYXZ8t8oU77T6Ki5qDG5V5DVZI3Ym5gqqXXtJYzET9piJvO6qiIcgljtOGlUH9H9QNLEbuF+RKIhL3pFAnF8S79Km2A3j9KFZw6prDR6/VeMffMrNSZLeYztzDGEzm35uz5q6j+qrKsuA4SfpbSOcBwaariOoKpb6JfogoJRgCqxR5O1AKR/Oqhdk6JOlKJk+tIXFmOczH7da/W93f8KGGve4iHRvz/e3vYA7exXIVkD8mc/VmIoT1kqh/uNGia/adnyCgvMpL8JXLJgY2DThpjHslUr0RTEpQJTLTka3D43YV37kM='
      #dest: /home/ '{{ item }}'/.ssh/id_rsa.pub
      #with_items:
      #- Webdeveloper
      #- Devopsengineer
      #- Projectmanager

      # publickey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCovvBkeLIDsvbCyQsMWtPWVgGVKcwAqRONiBJ9JyrVCQbruyMPutatjSlhNpYXKLlP4BXHrGrmAVqeI155li1fkNP5Il7viHRE0HvA3M2extNGDDCiX5f5OlIeT9p/D9OHvWWozLjN2NAGEW24feuzKPZb6Kyv2W3yHbiIU3wt8v50VAIA2+PAfElHp1jplGHQLmYuT6Cc26Pn3WYXZ8t8oU77T6Ki5qDG5V5DVZI3Ym5gqqXXtJYzET9piJvO6qiIcgljtOGlUH9H9QNLEbuF+RKIhL3pFAnF8S79Km2A3j9KFZw6prDR6/VeMffMrNSZLeYztzDGEzm35uz5q6j+qrKsuA4SfpbSOcBwaariOoKpb6JfogoJRgCqxR5O1AKR/Oqhdk6JOlKJk+tIXFmOczH7da/W93f8KGGve4iHRvz/e3vYA7exXIVkD8mc/VmIoT1kqh/uNGia/adnyCgvMpL8JXLJgY2DThpjHslUr0RTEpQJTLTka3D43YV37kM=
